#!/usr/bin/env sh
# Grayson Hansard, 2011
# info@fromconcentratesoftware.com

uuid=`uuidgen`
outdir="/tmp/munkiscript-tmp/$uuid"
mkdir -p $outdir
ext=`defaults read com.googlecode.munki.munkiimport pkginfo_extension 2> /dev/null`

wd=`pwd`

if [[ -d "$1" ]]; then
	cp "$1/*" $outdir
elif [[ -f "$1" ]]; then
	cp "$1" $outdir
fi

dmg=`basename "$1"`
hdiutil create -srcfolder /tmp/munkiscript-tmp/ "$dmg".dmg

echo "#!/usr/bin/env sh" > /tmp/munkiscript-tmp/postflight
echo "for script in /Library/Managed\ Installs/Scripts/$uuid/*; do if [[ \$script == *.sh ]]; then /bin/sh \"\$script\"; fi;if [[ \$script == *.rb ]]; then /usr/bin/ruby \"\$script\"; fi;if [[ \$script == *.py ]]; then /usr/bin/python \"\$script\"; fi;if [[ \$script == *.pl ]]; then /usr/bin/perl \"\$script\"; fi;done" >> /tmp/munkiscript-tmp/postflight

echo "#!/usr/bin/env sh" > /tmp/munkiscript-tmp/preflight
echo "if [[ ! -d /Library/Managed\ Installs/Scripts ]]; then" >> /tmp/munkiscript-tmp/preflight
echo "mkdir -p /Library/Managed\ Installs/Scripts" >> /tmp/munkiscript-tmp/preflight
echo "fi" >> /tmp/munkiscript-tmp/preflight

makepkginfo -i $uuid -d /Library/Managed\ Installs/Scripts --displayname="$dmg" --pkgname="$dmg" --preinstall_script=/tmp/munkiscript-tmp/preflight --postinstall_script=/tmp/munkiscript-tmp/postflight "$dmg.dmg" > "$dmg$ext"
defaults write "$wd/$dmg" name "$dmg"
rm -r /tmp/munkiscript-tmp


## Do imports if requested and possible.
repo=`defaults read com.googlecode.munki.munkiimport repo_path 2> /dev/null`
if [[ $repo == "" || ! -d "$repo" ]]; then
	exit 1
fi

echo "Would you like to import these tools into the repository? \c"
read should_import
if [[ $should_import == y* || $should_import == Y* ]]; then
	cp "$dmg.dmg" "$repo"/pkgs/
	cp "$dmg$ext" "$repo"/pkgsinfo/
fi

echo "Rebuild catalogs? \c"
read should_rebuild
if [[ $should_rebuild == y* || $should_rebuild == Y* ]]; then
	/usr/local/munki/makecatalogs $repo
fi
